python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/CleanseBoth.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/DeriveRenameAColumn.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/DeriveWithRecursiveDerive.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/DistinctMultipleColumns.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/DistinctOneColumn.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/ExistsInnerExpression.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/ExistsSimple.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/FilterWithAnd.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/GroupByAdvanceColumns.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
#python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/InPipeline.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/JoinCross.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/JoinSelf.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/JoinThreeTables.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/MultipleNodeswithsamename.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
#python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/NodeSimpleFilterwithalloperations.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/NonProwaterMarkPipeline.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/NotInNodePipeline.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/ParquetPipeline.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/SourceasAnotherPipelineTarget1.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/SplitRecursiveSplit.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/TargetReferencesAnother.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/TargetReferencesAnother2.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/UnionThreeTables.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/UnionThreeTablesDistinct.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
python pipelinehelper.py /Users/manoharm/infoworks/utils/backup/AutomationSpecs_MM_pipelines/UseMultipleTargetsInPipeline.json /Users/manoharm/github/rosie/content/datasets/df_manohar/
